apiVersion: v1
kind: Service
metadata:
  name: webapp-srv
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - name: tcp-webapp
      protocol: TCP
      port: 3000
      targetPort: 3000